export const staticClaimStatuses = [
  { claimStatusId: 1, statusName: "Settled" },
  { claimStatusId: 2, statusName: "Settled" },
  { claimStatusId: 3, statusName: "Claim sent to CEO- Bill processing" },
  { claimStatusId: 4, statusName: "Claim Denied" },
  { claimStatusId: 5, statusName: "Enhancement Denied" },
  { claimStatusId: 6, statusName: "Cancelled" },
  { claimStatusId: 7, statusName: "Claim sent to Claim Executive" },
  { claimStatusId: 8, statusName: "Pre Auth Submitted to Payer" },
  { claimStatusId: 9, statusName: "Discharge Update" },
  { claimStatusId: 10, statusName: "Claim Approved" },
  { claimStatusId: 11, statusName: "AUDITCOMMITTEE recommended for approval" },
  { claimStatusId: 12, statusName: "Settlement Initiated" },
  { claimStatusId: 13, statusName: "CEO Claim Approved" },
  { claimStatusId: 14, statusName: "Claim Stopped Due to Patient Feedback not Submitted - CEO" },
  { claimStatusId: 15, statusName: "Enhancement Approved" },
  { claimStatusId: 16, statusName: "Cancelled by MEDCO" },
  { claimStatusId: 17, statusName: "Claim Paid" },
  { claimStatusId: 18, statusName: "Claim in Progress" },
  { claimStatusId: 19, statusName: "Trust Doctor Rejected" },
  { claimStatusId: 20, statusName: "Failed Transaction to Patient Account" },
  { claimStatusId: 21, statusName: "Preauthorisation PPD Rejected" },
  { claimStatusId: 22, statusName: "EO Rejected" },
  { claimStatusId: 23, statusName: "Preauthorisation PTD Rejected" },
];